apiVersion: v1
kind: ConfigMap
metadata:
  name: properties-files
data:
  gateway-properties: |
    spring:
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
      kafka:
        listener:
          concurrency: 16
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 20000
          properties:
            max.poll.interval.ms: 30000
            session.timeout.ms: 60000
      jpa:
        show-sql: false
  browser-blackhole-properties: |
    spring:
      application:
        name: plagiarism-check-candidate-browser-blackhole
      kafka:
        listener:
          concurrency: 48
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 60000
          properties:
            max.poll.interval.ms: 1800000
            session.timeout.ms: 180000
            partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 96
      jpa:
        show-sql: false
    ise:
      receive-timeout: 1800
  browser-coc-properties: |
    spring:
      application:
        name: plagiarism-check-candidate-browser-coc
      kafka:
        listener:
          concurrency: 24
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 60000
          properties:
            max.poll.interval.ms: 1800000
            session.timeout.ms: 180000
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 48
      jpa:
        show-sql: false
    ise:
      receive-timeout: 1800
  browser-domain-properties: |
    spring:
      application:
        name: plagiarism-check-candidate-browser-domain
      kafka:
        listener:
          concurrency: 16
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 60000
          properties:
            max.poll.interval.ms: 1800000
            session.timeout.ms: 180000
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 36
      jpa:
        show-sql: false
    ise:
      receive-timeout: 1800
  browser-group-properties: |
    spring:
      application:
        name: plagiarism-check-candidate-browser-group
      kafka:
        listener:
          concurrency: 16
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 60000
          properties:
            max.poll.interval.ms: 1800000
            session.timeout.ms: 180000
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 36
      jpa:
        show-sql: false
    ise:
      receive-timeout: 1800
  browser-union-properties: |
    spring:
      application:
        name: plagiarism-check-candidate-browser-union
      kafka:
        listener:
          concurrency: 16
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 60000
          properties:
            max.poll.interval.ms: 1800000
            session.timeout.ms: 180000
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 36
      jpa:
        show-sql: false
    ise:
      receive-timeout: 1800
  checker-properties: |
    spring:
      kafka:
        listener:
          concurrency: 48
        consumer:
          max-poll-records: 1
          enable-auto-commit: false
          heartbeat-interval: 60000
          properties:
            max.poll.interval.ms: 900000
            session.timeout.ms: 180000
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 96
      jpa:
        show-sql: false
    ise:
      receive-timeout: 600
  extractor-properties: |
    spring:
      kafka:
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
        hikari:
          minimum-idle: 5
          maximum-pool-size: 36  
      jpa:
        show-sql: false
    server:
      netty:
        connection-timeout: 600000    
    ise:
      bootstrap-server: 115.68.158.77:2114
      receive-timeout: 600

  window-properties: |
    spring:
      kafka:
        bootstrap-servers: 115.68.157.201:9092 115.68.157.202:9092 115.68.157.203:9092
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check


  ticket-properties: |
    spring:
      kafka:
        bootstrap-servers: 115.68.157.201:9092 115.68.157.202:9092 115.68.157.203:9092
      datasource:
        url: jdbc:mariadb://115.68.158.74:3306/plagiarism_check
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-cm
data:
  TZ: Asia/Seoul
