apiVersion: v1
kind: Service
metadata:
  name: precisecheck-client
  namespace: plagiarism-agent
spec:
  selector:
    app: precisecheck-client
  ports:
    - port: 8080
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: precisecheck-client
  namespace: plagiarism-agent
  labels:
    app: precisecheck-client
spec:
  replicas: 1
  template:
    metadata:
      name: precisecheck-client
      labels:
        app: precisecheck-client
    spec:
      containers:
        - name: precisecheck-client
          image: docker.muhayu.com/plagiarism-client/plagiarism-precisecheck:1.0.0.build-20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: "APM_OPTION"
              value: "-javaagent:elastic-apm-agent-1.32.0.jar -Delastic.apm.service_name=plagiarism-extractor -Delastic.apm.server_urls=http://115.68.158.11:8200 -Delastic.apm.application_packages=com.muhayu -Delastic.apm.log_ecs_reformatting=SHADE -Delastic.apm.log_level=INFO"
            - name: "JAVA_OPTION"
              value: "-Dspring.profiles.active=prod -Djava.net.preferIPv4Stack=true -Djsse.enableSNIExtension=false -Dfile.encoding=UTF8 -Dfile.client.encoding=UTF8 -Dclient.encoding.override=UTF8 -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=8"
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: env-cm
          resources:
            requests:
              cpu: 2000m
              memory: 8G
            limits:
              cpu: 2000m
              memory: 8G
          readinessProbe:
            tcpSocket:
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 180
          #          livenessProbe:
          #            tcpSocket:
          #              port: 8081
          #            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /precisecheck/properties
              name: properties-file
      restartPolicy: Always
      volumes:
        - name: properties-file
          configMap:
            name: client-precisecheck-properties
            items:
              - key: precisecheck-properties
                path: application.yml
  selector:
    matchLabels:
      app: precisecheck-client
