apiVersion: v1
kind: Service
metadata:
  name: restapi-client
  namespace: plagiarism-agent
spec:
  selector:
    app: restapi-client
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-client
  namespace: plagiarism-agent
  labels:
    app: restapi-client
spec:
  replicas: 2
  template:
    metadata:
      name: restapi-client
      labels:
        app: restapi-client
    spec:
      containers:
        - name: restapi-client
          image: docker.muhayu.com/plagiarism-client/plagiarism-restapi:1.0.0.build-10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: "APM_OPTION"
              value: "-javaagent:elastic-apm-agent-1.32.0.jar -Delastic.apm.service_name=plagiarism-extractor -Delastic.apm.server_urls=http://115.68.158.11:8200 -Delastic.apm.application_packages=com.muhayu -Delastic.apm.log_ecs_reformatting=SHADE -Delastic.apm.log_level=INFO"
            - name: "JAVA_OPTION"
              value: "-Djava.net.preferIPv4Stack=true -Djsse.enableSNIExtension=false -Dfile.encoding=UTF8 -Dfile.client.encoding=UTF8 -Dclient.encoding.override=UTF8 -Dspring.profiles.active=prod"
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: env-cm
          resources:
            requests:
              cpu: 2000m
              memory: 8G
            limits:
              cpu: 2000m
              memory: 8G
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 180
          #          livenessProbe:
          #            tcpSocket:
          #              port: 8081
          #            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /restapi/properties
              name: properties-file
      restartPolicy: Always
      volumes:
        - name: properties-file
          configMap:
            name: client-restapi-properties
            items:
              - key: restapi-properties
                path: application.yml
  selector:
    matchLabels:
      app: restapi-client
