apiVersion: v1
kind: ConfigMap
metadata:
  name: client-restapi-properties
data:
  restapi-properties: |
    spring:
      application:
        name: plagiarism-client-restapi
    
      config:
        activate:
          on-profile: prod
      kafka:
        bootstrap-servers:
          - 115.68.157.201:9092
          - 115.68.157.202:9092
          - 115.68.157.203:9092
        consumer:
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          max-poll-records: 1
          candidate:
            group-id: ${spring.application.name}-candidate
          check:
            group-id: ${spring.application.name}-check
          properties:
            max.poll.interval.ms: 60000
            session.timeout.ms: 180000
          heartbeat-interval: 60000
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          acks: all
        properties:
          spring.json.trusted.packages: com.muhayu.*
        listener:
          concurrency: 3
          ack-mode: manual_immediate
      sleuth:
        enabled: true
        sampler:
          probability: 1.0
      zipkin:
        base-url: http://115.68.157.183:9411
        enabled: true
        sender:
          type: kafka
    
      datasource:
        url: jdbc:mariadb://115.68.157.39:3306/ckpass?characterEncoding=utf8
        username: unit2
        password: apxkqjtm2!
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:
          connection-test-query: select 1
          minimum-idle: 1
          maximum-pool-size: 5
          pool-name: SpringBootJPAHikariCP
          idle-timeout: 15000
          connection-timeout: 15000
          validation-timeout: 15000
          max-lifetime: 580000
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            useLocalTransactionState: true
            rewriteBatchedStatements: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false
      jpa:
        hibernate:
         ddl-auto: validate
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        show-sql: true
        open-in-view: false
  
    feign:
      client:
        config:
          default:
            connectTimeout: 60000
            readTimeout: 30000
  
    server:
      port: 8080
      undertow:
        accesslog:
          dir: logs/
          enabled: true
  
    logging:
      file:
        name: logs/plagiarism-check-restapi.log

    plagiarism-check:
      client:
        agent-window:
          url: http://window.plagiarism-agent.svc.cluster.local:8080
          ext-url: http://window.plagiarism-agent.svc.cluster.local:8080
          path: /window
        check-property:
          api: http://www.copykiller.co.kr/?module=copykiller&act=procGetCheckPropertyList
          api-pass: http://ckpass.copykiller.com/?module=copykiller&act=procGetCheckPropertyList
        candidate-count: 10000
  
      copyratio:
        producer:
          produce-topic: queuing.plagiarism-check.precise-check.request

